# Generated by Django 5.2 on 2026-05-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_email_verified_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, default='', help_text='Firebase Cloud Messaging device token for push notifications.', max_length=255, verbose_name='FCM token'),
        ),
    ]
