# Generated by Django 5.2 on 2026-05-23 16:51

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('scooter', 'Scooter'), ('bicycle', 'Bicycle'), ('moped', 'Moped')], max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('charging', 'Charging'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', max_length=20, verbose_name='status')),
                ('battery_level', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='battery level (%)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QR code')),
                ('zone', models.CharField(blank=True, max_length=100, verbose_name='zone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
