# Generated by Django 5.2 on 2026-05-24 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='status')),
                ('start_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='start latitude')),
                ('start_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='start longitude')),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='end latitude')),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='end longitude')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (seconds)')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='distance (km)')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='payment amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to=settings.AUTH_USER_MODEL, verbose_name='driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'ride',
                'verbose_name_plural': 'rides',
                'ordering': ['-started_at'],
            },
        ),
    ]
