# Generated by Django 5.2 on 2026-05-23 18:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactivityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='opened at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('threshold_minutes', models.PositiveSmallIntegerField(help_text='Inactivity threshold (in minutes) that triggered this alert.', verbose_name='threshold (minutes)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactivity_alerts', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'inactivity alert',
                'verbose_name_plural': 'inactivity alerts',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['vehicle', 'closed_at'], name='tracking_in_vehicle_7d89a0_idx')],
            },
        ),
    ]
