# Generated by Django 5.2 on 2026-05-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_threshold_minutes', models.PositiveSmallIntegerField(default=30, help_text='Fallback used for vehicle types not listed below.', verbose_name='default threshold (minutes)')),
                ('scooter_threshold_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='scooter threshold (minutes)')),
                ('bicycle_threshold_minutes', models.PositiveSmallIntegerField(default=20, verbose_name='bicycle threshold (minutes)')),
                ('moped_threshold_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='moped threshold (minutes)')),
            ],
            options={
                'verbose_name': 'tracking configuration',
                'verbose_name_plural': 'tracking configuration',
            },
        ),
    ]
