# Generated by Django 5.2 on 2026-05-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='date')),
                ('total_rides', models.PositiveIntegerField(default=0, verbose_name='total rides')),
                ('completed_rides', models.PositiveIntegerField(default=0, verbose_name='completed rides')),
                ('cancelled_rides', models.PositiveIntegerField(default=0, verbose_name='cancelled rides')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total revenue (AZN)')),
                ('active_vehicles', models.PositiveIntegerField(default=0, verbose_name='active vehicles (snapshot)')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
            ],
            options={
                'verbose_name': 'daily report',
                'verbose_name_plural': 'daily reports',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ZoneActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('zone', models.CharField(db_index=True, max_length=100, verbose_name='zone')),
                ('rides_started', models.PositiveIntegerField(default=0, verbose_name='rides started')),
                ('rides_ended', models.PositiveIntegerField(default=0, verbose_name='rides ended')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='computed at')),
            ],
            options={
                'verbose_name': 'zone activity report',
                'verbose_name_plural': 'zone activity reports',
                'ordering': ['-date', 'zone'],
                'unique_together': {('date', 'zone')},
            },
        ),
    ]
